### ISSUE TITLE
Ratatui dependency outdated.

### ISSUE THREAD

**Issue by airblast-dev** [arkbig/throbber-widgets-tui#12]
Two days ago version `0.27.0`  was released for `ratatui`. Currently this makes the library unusable with the newer version as the `Widget, WidgetRef, ...` traits are implemented for the older version of `ratatui`.

I also read the breaking changes, and tested it in my own application. From what I see there aren't any breaking changes. So should be just a version bump in `Cargo.toml`

**Comment by arkbig** [comment]
Thank you for contacting us.
We have updated ratatui and released [v0.6.0](https://github.com/arkbig/throbber-widgets-tui/releases/tag/v0.6.0)
