### ISSUE TITLE
ratatui

### ISSUE THREAD

**Issue by lcmgh** [arkbig/throbber-widgets-tui#2]
The ratatui crate is the tui successor. Does it also work with it?

**Comment by arkbig** [comment]
Thanks for posting the issue, I understand the tui-rs situation.
I built it using ratatui for now and it works as is. I uploaded it to branch [feature/ratatui](https://github.com/arkbig/throbber-widgets-tui/tree/feature/ratatui)

I would like to be able to switch between tui and ratatui with the features flag when `cargo add` in the future. In the new version, I would like to default to ratatui and be able to switch to tui-rs while it is available.

**Comment by arkbig** [comment]
Version 0.2.0 is now available.
Use ratatui by default. If you want to use tui, please use the features flag `--no-default-features --features=tui-rs`.

Thank you for your posting.
