### ISSUE TITLE
Release 0.7.2 is not semver compatible due to ratatui's API being exposed

### ISSUE THREAD

**Issue by jkelleyrtp** [arkbig/throbber-widgets-tui#21]
Since Ratatui's API is re-exported from this crate, you cannot upgrade to ratatui 29 without breaking this crate's API.

This means 0.7.2 breaks semver and therefore breaks downstream builds.

Please yank 0.7.2 and re-release this crate under 0.8.0 :)

Thanks!

**Comment by arkbig** [comment]
Indeed it is. Thanks for getting back to me as soon as possible.
